apiVersion: v1
baseDomain: emeatam.support
compute:
- architecture: amd64
  hyperthreading: Enabled
  name: worker
  platform: {}
  replicas: 2
controlPlane:
  architecture: amd64
  hyperthreading: Enabled
  name: master
  platform: 
    aws:
      type: m5.12xlarge
  replicas: 3
metadata:
  creationTimestamp: null
  name: iscsi-demo
networking:
  clusterNetwork:
  - cidr: 10.128.0.0/14
    hostPrefix: 23
  machineNetwork:
  - cidr: 10.0.0.0/16
  networkType: OpenShiftSDN
  serviceNetwork:
  - 172.30.0.0/16
platform:
  aws:
    region: us-west-2
    userTags:
      user: dmoessne
      project: iscsi-demo
publish: External
pullSecret: '<redacted>'
sshKey: |
  ssh-rsa <redacted>
