apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
 name: openshift-storage-operatorgroup
 namespace: openshift-storage
spec:
 selector:
    matchLabels:
      cluster.ocs.openshift.io/openshift-storage: ""
      node-role.kubernetes.io/master: ""
 targetNamespaces:
 - openshift-storage
