---
kind: DeploymentConfig
apiVersion: apps.openshift.io/v1
metadata:
  name: hello-openshift
spec:
  replicas: 50
  template:
    metadata:
      labels:
        app: hello-openshift
    spec:
      containers:
      - name: hello-openshift
        image: openshift/hello-openshift:latest
        ports:
        - containerPort: 80
